apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls-letsencrypt
  namespace: ${REGISTRY_NAMESPACE}
spec:
  secretName: registry-tls
  dnsNames:
    - ${REGISTRY_DOMAIN}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
